apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: keda-core
  namespace: flux-system
spec:
  interval: 1m
  url: https://kedacore.github.io/charts

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  interval: 5m
  chart:
    spec:
      chart: keda
      version: '2.3.0'
      sourceRef:
        kind: HelmRepository
        name: keda-core
        namespace: flux-system
      interval: 1m
