apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: open-policy-agent
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    tag: v3.4.0
  secretRef:
    name: flux-system
  ignore: |
    /*
    !/deploy
    /deploy/experimental
  url: ssh://git@github.com/open-policy-agent/gatekeeper

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: open-policy-agent-git
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: open-policy-agent
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: open-policy-agent
    namespace: flux-system
