apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kuberhealthy
  namespace: flux-system
spec:
  interval: 10m
  url: https://kuberhealthy.github.io/kuberhealthy/helm-repos

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kuberhealthy
  namespace: kuberhealthy
spec:
  interval: 5m
  chart:
    spec:
      chart: kuberhealthy
      version: '69'
      sourceRef:
        kind: HelmRepository
        name: kuberhealthy
        namespace: flux-system
      interval: 1m
