apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: keptn
  namespace: flux-system
spec:
  interval: 1m
  url: https://storage.googleapis.com/keptn-installer

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keptn
  namespace: keptn
spec:
  interval: 5m
  chart:
    spec:
      chart: keptn
      version: '0.8.3'
      sourceRef:
        kind: HelmRepository
        name: keptn
        namespace: flux-system
      interval: 1m
