apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: stateless
  namespace: vela-system
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    kube:
      parameters:
      - name: image
        required: true
        type: string
        fieldPaths:
        - "spec.template.spec.containers[0].image"
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: some-site
        spec:
          selector:
            matchLabels:
              app: busybox
          replicas: 1
          template:
            metadata:
              labels:
                app: busybox
            spec:
              containers:
              - name: context.appName
                imagePullPolicy: IfNotPresent
                command:
                - "sleep"
                - "infinity"
---

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: some-site
  namespace: default
spec:
  components:
    - name: some-site
      type: stateless
      properties:
        image: "busybox"
