apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubevela
  namespace: flux-system
spec:
  url: https://kubevelacharts.oss-accelerate.aliyuncs.com/core
  interval: 10m

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubevela
  namespace: vela-system
spec:
  interval: 5m
  chart:
    spec:
      chart: vela-core
      interval: 10m
      version: 1.0.4
      sourceRef:
        kind: HelmRepository
        name: kubevela
        namespace: flux-system
  install:
    remediation:
      retries: 3
