apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: development
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
  - name: monitoring
  - name: kubevela
  - name: kubevela-custom-definitions
  - name: kubevela-trait-definitions
  path: ./cluster/namespaces/development
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: production
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
  - name: monitoring
  - name: kubevela
  - name: kubevela-custom-definitions
  - name: kubevela-trait-definitions
  path: ./cluster/namespaces/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
