apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 20m0s
  path: ./cluster/infrastructure
  prune: true
  dependsOn:
  - name: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: applications
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
  - name: infrastructure
  - name: monitoring
  - name: kubevela-custom-definitions
  - name: kubevela-trait-definitions
  path: ./cluster/applications
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
