apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: instrumented-app
  namespace: somenamespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: instrumented-app
    envSourceContainerName: instrumented-app
  pollingInterval: 30
  cooldownPeriod:  300
  minReplicaCount: 2
  maxReplicaCount: 10
  advanced:
    restoreToOriginalReplicaCount: false
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-operated.monitoring.svc.cluster.local:9090
      metricName: http_requests_total
      query: sum(rate(http_requests_total{deployment="instrumented-app"}[2m]))
      threshold: '100'
